font_family FiraCode Nerd Font Mono

font_size 16.0

cursor_trail 1
cursor_blink yes
cursor_blink_interval 800

background_opacity 1

window_margin_width 10

include Catppuccin-Mocha.conf
bold_is_bright no
